import { IconType } from "react-icons";

import {
  HiArrowPath,
  HiArrowRight,
  HiArrowTopRightOnSquare,
  HiArrowUpRight,
  HiCalendarDays,
  HiChartPie,
  HiCheckCircle,
  HiCurrencyDollar,
  HiEnvelope,
  HiMapPin,
  HiOutlineDocument,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineLink,
  HiOutlineRocketLaunch,
  HiPhone,
  HiSparkles,
  HiWallet,
} from "react-icons/hi2";

import {
  PiBookBookmarkDuotone,
  PiCrownSimpleDuotone,
  PiGridFourDuotone,
  PiHouseDuotone,
  PiImageDuotone,
  PiUserCircleDuotone,
} from "react-icons/pi";

import {
  SiFigma,
  SiJavascript,
  SiNextdotjs,
  SiSupabase,
  SiTradingview,
} from "react-icons/si";

import {
  FaDiscord,
  FaFacebook,
  FaGithub,
  FaInfinity,
  FaInstagram,
  FaLinkedin,
  FaPinterest,
  FaReddit,
  FaTelegram,
  FaThreads,
  FaWhatsapp,
  FaX,
  FaXTwitter,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  crown: PiCrownSimpleDuotone,
  wallet: HiWallet,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  repeat: HiArrowPath,
  location: HiMapPin,
  check: HiCheckCircle,
  sparkles: HiSparkles,
  phone: HiPhone,
  infinity: FaInfinity,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  instagram: FaInstagram,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  tradingview: SiTradingview,
  currencyDollar: HiCurrencyDollar,
  chartPie: HiChartPie,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
