import {
  HiArrowUpRight,
  HiChevronDown,
  HiChevronLeft,
  HiChevronRight,
  HiChevronUp,
  HiOutlineArrowPath,
  HiOutlineArrowsPointingIn,
  HiOutlineArrowsPointingOut,
  HiOutlineArrowTurnDownLeft,
  HiOutlineCalendar,
  HiOutlineCheck,
  HiOutlineCheckCircle,
  HiOutlineClipboard,
  HiOutlineComputerDesktop,
  HiOutlineDocumentDuplicate,
  HiOutlineExclamationCircle,
  HiOutlineExclamationTriangle,
  HiOutlineEye,
  HiOutlineEyeDropper,
  HiOutlineEyeSlash,
  HiOutlineFaceSmile,
  HiOutlineInformationCircle,
  HiOutlineLink,
  HiOutlineMagnifyingGlass,
  HiOutlineMinus,
  HiOutlineMoon,
  HiOutlinePause,
  HiOutlinePlay,
  HiOutlinePlus,
  HiOutlineQuestionMarkCircle,
  HiOutlineShieldCheck,
  HiOutlineSparkles,
  HiOutlineSun,
  HiOutlineUser,
  HiOutlineXMark,
} from "react-icons/hi2";
import {
  IoAtOutline,
  IoFastFoodOutline,
  IoFlagOutline,
  IoFootballOutline,
  IoGiftOutline,
  IoGlobeOutline,
  IoPawOutline,
} from "react-icons/io5";
import { LuTextCursorInput } from "react-icons/lu";
export const iconLibrary = {
  chevronUp: HiChevronUp,
  chevronDown: HiChevronDown,
  chevronRight: HiChevronRight,
  chevronLeft: HiChevronLeft,
  refresh: HiOutlineArrowPath,
  light: HiOutlineSun,
  dark: HiOutlineMoon,
  help: HiOutlineQuestionMarkCircle,
  info: HiOutlineInformationCircle,
  warning: HiOutlineExclamationTriangle,
  danger: HiOutlineExclamationCircle,
  checkbox: HiOutlineCheck,
  check: HiOutlineCheckCircle,
  copy: HiOutlineDocumentDuplicate,
  eyeDropper: HiOutlineEyeDropper,
  clipboard: HiOutlineClipboard,
  person: HiOutlineUser,
  close: HiOutlineXMark,
  link: HiOutlineLink,
  arrowUpRight: HiArrowUpRight,
  minus: HiOutlineMinus,
  plus: HiOutlinePlus,
  calendar: HiOutlineCalendar,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  search: HiOutlineMagnifyingGlass,
  security: HiOutlineShieldCheck,
  sparkle: HiOutlineSparkles,
  computer: HiOutlineComputerDesktop,
  minimize: HiOutlineArrowsPointingIn,
  maximize: HiOutlineArrowsPointingOut,
  smiley: HiOutlineFaceSmile,
  paw: IoPawOutline,
  food: IoFastFoodOutline,
  ball: IoFootballOutline,
  world: IoGlobeOutline,
  gift: IoGiftOutline,
  symbol: IoAtOutline,
  flag: IoFlagOutline,
  wordmark: LuTextCursorInput,
  enter: HiOutlineArrowTurnDownLeft,
  play: HiOutlinePlay,
  pause: HiOutlinePause,
};
//# sourceMappingURL=icons.js.map
