spec:
  name: dynamic-capital
  static_sites:
    - name: landing
      source_dir: apps/landing
      build_command: "npm ci && npm run build && npm --prefix ../.. run upload-assets"
      output_dir: "dist"
      routes:
        - path: /
      index_document: index.html
      catchall_document: index.html
      envs:
        - key: CDN_BUCKET
          scope: RUN_AND_BUILD_TIME
        - key: CDN_REGION
          scope: RUN_AND_BUILD_TIME
        - key: CDN_ACCESS_KEY
          scope: RUN_AND_BUILD_TIME
        - key: CDN_SECRET_KEY
          scope: RUN_AND_BUILD_TIME
  services:
    - name: web
      source_dir: apps/web
      environment_slug: node-js
      build_command: "npm ci && npm run build"
      run_command: "npm run start"
      http_port: 8080
      envs:
        - key: NEXT_PUBLIC_SUPABASE_URL
          scope: RUN_TIME
        - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
          scope: RUN_TIME
        - key: SUPABASE_SERVICE_ROLE_KEY
          scope: RUN_TIME
      routes:
        - path: /app
