spec:
  name: dynamic-capital
  services:
    - name: web
      source_dir: apps/web
      environment_slug: node-js
      build_command: "npm ci && npm run build"
      run_command: "PORT=$PORT npm start"
      http_port: 8080
      envs:
        - key: SITE_URL
          value: https://urchin-app-macix.ondigitalocean.app
          scope: RUN_AND_BUILD_TIME
        - key: NEXT_PUBLIC_SUPABASE_URL
          scope: RUN_AND_BUILD_TIME
        - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
          scope: RUN_AND_BUILD_TIME
        - key: SUPABASE_SERVICE_ROLE_KEY
          scope: RUN_TIME
      routes:
        - path: /
