spec:
  name: dynamic-capital
  region: sgp
  features:
    - buildpack-stack=ubuntu-22
  alerts:
    - rule: DEPLOYMENT_FAILED
    - rule: DOMAIN_FAILED
  envs:
    - key: NODE_ENV
      value: production
      scope: RUN_AND_BUILD_TIME
    - key: NPM_CONFIG_PRODUCTION
      value: "false"
      scope: RUN_AND_BUILD_TIME
    - key: NEXT_TELEMETRY_DISABLED
      value: "1"
      scope: RUN_AND_BUILD_TIME
    - key: SITE_URL
      value: https://dynamic-capital-qazf2.ondigitalocean.app
      scope: RUN_AND_BUILD_TIME
    - key: NEXT_PUBLIC_SITE_URL
      value: https://dynamic-capital-qazf2.ondigitalocean.app
      scope: RUN_AND_BUILD_TIME
    - key: ALLOWED_ORIGINS
      value: https://dynamic-capital-qazf2.ondigitalocean.app,https://dynamic-capital.ondigitalocean.app,https://dynamic.capital,https://dynamic-capital.vercel.app,https://dynamic-capital.lovable.app
      scope: RUN_AND_BUILD_TIME
    - key: MINIAPP_ORIGIN
      value: https://dynamic-capital-qazf2.ondigitalocean.app,https://dynamiccapital.ton,https://t.me
      scope: RUN_AND_BUILD_TIME
    - key: TELEGRAM_WEBHOOK_URL
      value: https://dynamic-capital-qazf2.ondigitalocean.app/webhook
      scope: RUN_AND_BUILD_TIME
    - key: NEXT_PUBLIC_SUPABASE_URL
      value: https://qeejuomcapbdlhnjqjcc.supabase.co
      scope: RUN_AND_BUILD_TIME
    - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
      value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlZWp1b21jYXBiZGxobmpxamNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDE4MTUsImV4cCI6MjA2OTc3NzgxNX0.GfK9Wwx0WX_GhDIz1sIQzNstyAQIF2Jd6p7t02G44zk
      scope: RUN_AND_BUILD_TIME
    - key: SUPABASE_SERVICE_ROLE_KEY
      scope: RUN_TIME
    - key: CDN_BUCKET
      scope: RUN_AND_BUILD_TIME
    - key: CDN_REGION
      scope: RUN_AND_BUILD_TIME
    - key: CDN_ACCESS_KEY
      scope: RUN_AND_BUILD_TIME
    - key: CDN_SECRET_KEY
      scope: RUN_AND_BUILD_TIME
  services:
    - name: dynamic-capital
      source_dir: .
      github:
        repo: Dynamic-Capital/Dynamic-Capital
        branch: main
        deploy_on_push: true
      environment_slug: node-js
      instance_count: 1
      instance_size_slug: basic-xxs
      build_command: npm run build:web
      run_command: npm run start:do
      http_port: 3000
      routes:
        - path: /
      health_check:
        http_path: /healthz
      envs:
        - key: SITE_URL
          value: https://dynamic-capital-qazf2.ondigitalocean.app
          scope: RUN_AND_BUILD_TIME
        - key: NEXT_PUBLIC_SITE_URL
          value: https://dynamic-capital-qazf2.ondigitalocean.app
          scope: RUN_AND_BUILD_TIME
        - key: ALLOWED_ORIGINS
          value: https://dynamic-capital-qazf2.ondigitalocean.app,https://dynamic-capital.ondigitalocean.app,https://dynamic.capital,https://dynamic-capital.vercel.app,https://dynamic-capital.lovable.app
          scope: RUN_AND_BUILD_TIME
        - key: MINIAPP_ORIGIN
          value: https://dynamic-capital-qazf2.ondigitalocean.app,https://dynamiccapital.ton,https://t.me
          scope: RUN_AND_BUILD_TIME
        - key: TELEGRAM_WEBHOOK_URL
          value: https://dynamic-capital-qazf2.ondigitalocean.app/webhook
          scope: RUN_AND_BUILD_TIME
  static_sites: []
  workers: []
  jobs: []
  functions: []
