spec:
  name: dynamic-capital
  envs:
    - key: CDN_BUCKET
      scope: RUN_AND_BUILD_TIME
    - key: CDN_REGION
      scope: RUN_AND_BUILD_TIME
    - key: CDN_ACCESS_KEY
      scope: RUN_AND_BUILD_TIME
    - key: CDN_SECRET_KEY
      scope: RUN_AND_BUILD_TIME
    - key: SITE_URL
      value: https://urchin-app-macix.ondigitalocean.app
      scope: RUN_AND_BUILD_TIME
    - key: NEXT_PUBLIC_SUPABASE_URL
      scope: RUN_AND_BUILD_TIME
    - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
      scope: RUN_AND_BUILD_TIME
    - key: SUPABASE_SERVICE_ROLE_KEY
      scope: RUN_TIME
  static_sites:
    - name: landing
      source_dir: apps/landing
      output_dir: public
      index_document: index.html
      build_command: "npm ci && npm run build && npm --prefix ../.. run upload-assets"
      routes:
        - path: /
  services:
    - name: web
      source_dir: apps/web
      environment_slug: node-js
      build_command: "npm ci && npm run build"
      run_command: "PORT=$PORT npm start"
      http_port: 8080
      routes:
        - path: /
