"""Quantum orchestration primitives for Dynamic Capital."""

from __future__ import annotations

from .engine import (
    DynamicQuantumEngine,
    QuantumEnvironment,
    QuantumPulse,
    QuantumResonanceFrame,
)
from .collapse_cycle import (
    ConsciousCollapseEngine,
    DomainConfig,
    DomainSnapshot,
    LindbladChannel,
)
from .training import (
    EngineTrainingAdapter,
    expectation_value_cost,
    fidelity_cost,
    ParameterShiftResult,
    ParameterShiftTrainer,
    TrainingTelemetry,
)
from .hedge import (
    AdaptiveLiquidityModel,
    BasisRiskTracker,
    CrossAssetHedge,
    DynamicCostModel,
    DynamicHedgePortfolio,
    HedgeCalibrationResult,
    HedgeEffectivenessMonitor,
    HedgeRatioInstruction,
    MeanReversionSignal,
    PortfolioHolding,
    QuantumDynamicHedge,
    QuantumHedgeOptimizer,
    QuantumHedgePlan,
    QuantumSkewExposure,
    QuantumVolatilityHedge,
    TailHedgePortfolio,
    VolatilityBucket,
    adaptive_hedge_calibration,
    black_swan_hedge_strategy,
    calculate_quantum_correlations,
    calibrate_hedge_model,
    cross_asset_quantum_hedge,
    hedging_framework,
    kalman_filter_hedge_ratios,
    minimum_variance_hedge,
    multi_regime_dataset,
    quantum_anomaly_detection,
    quantum_cointegration_test,
    quantum_derivatives,
    quantum_neural_network,
    quantum_pairs_trading_hedge,
    quantum_value_at_risk,
)

__all__ = [
    "DynamicQuantumEngine",
    "QuantumEnvironment",
    "QuantumPulse",
    "QuantumResonanceFrame",
    "ConsciousCollapseEngine",
    "DomainConfig",
    "DomainSnapshot",
    "LindbladChannel",
    "EngineTrainingAdapter",
    "expectation_value_cost",
    "fidelity_cost",
    "ParameterShiftResult",
    "ParameterShiftTrainer",
    "TrainingTelemetry",
    "AdaptiveLiquidityModel",
    "BasisRiskTracker",
    "CrossAssetHedge",
    "DynamicCostModel",
    "DynamicHedgePortfolio",
    "HedgeCalibrationResult",
    "HedgeEffectivenessMonitor",
    "HedgeRatioInstruction",
    "MeanReversionSignal",
    "PortfolioHolding",
    "QuantumDynamicHedge",
    "QuantumHedgeOptimizer",
    "QuantumHedgePlan",
    "QuantumSkewExposure",
    "QuantumVolatilityHedge",
    "TailHedgePortfolio",
    "VolatilityBucket",
    "adaptive_hedge_calibration",
    "black_swan_hedge_strategy",
    "calculate_quantum_correlations",
    "calibrate_hedge_model",
    "cross_asset_quantum_hedge",
    "hedging_framework",
    "kalman_filter_hedge_ratios",
    "minimum_variance_hedge",
    "multi_regime_dataset",
    "quantum_anomaly_detection",
    "quantum_cointegration_test",
    "quantum_derivatives",
    "quantum_neural_network",
    "quantum_pairs_trading_hedge",
    "quantum_value_at_risk",
]
