# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.6.1

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dynamic-cluster-control-plane-pod
  name: dynamic-cluster-control-plane-pod
spec:
  containers:
  - env:
    - name: KUBECONFIG
      value: /etc/kubernetes/admin.conf
    - name: TERM
      value: xterm
    - name: HOSTNAME
      value: dynamic-cluster-control-plane
    image: docker.io/kindest/node@sha256:7416a61b42b1662ca6ca89f02028ac133a309a2a30ba309614e8ec94d976dc5a
    name: dynamic-cluster-control-plane
    ports:
    - containerPort: 80
      hostPort: 9090
    - containerPort: 443
      hostPort: 9443
    - containerPort: 6443
      hostIP: 127.0.0.1
      hostPort: 51505
    securityContext:
      privileged: true
      procMount: Unmasked
    tty: true
    volumeMounts:
    - mountPath: /lib/modules
      name: lib-modules-host-0
      readOnly: true
    - mountPath: /tmp
      name: tmp-1
    - mountPath: /run
      name: tmp-2
    - mountPath: /var
      name: 94027cafdb44a93e7045438ee9d5f28ecc0aea245871384d894c7381039431ce-pvc
  hostname: dynamic-cluster-control-plane
  volumes:
  - hostPath:
      path: /lib/modules
      type: Directory
    name: lib-modules-host-0
  - emptyDir:
      medium: Memory
    name: tmp-1
  - emptyDir:
      medium: Memory
    name: tmp-2
  - name: 94027cafdb44a93e7045438ee9d5f28ecc0aea245871384d894c7381039431ce-pvc
    persistentVolumeClaim:
      claimName: 94027cafdb44a93e7045438ee9d5f28ecc0aea245871384d894c7381039431ce
