"""Autogenerated placeholder build module for dynamic_message_queue."""

from __future__ import annotations

from typing import Any, Mapping

from dynamic_build_stub import build_placeholder, main_placeholder

__all__ = ("build", "main")


def build(*args: Any, **kwargs: Any) -> Mapping[str, Any]:
    """Proxy to the shared build placeholder for dynamic_message_queue."""
    return build_placeholder("dynamic_message_queue", *args, **kwargs)


def main() -> int:
    """Entry point for "python -m dynamic_message_queue.build"."""
    return main_placeholder("dynamic_message_queue")


if __name__ == "__main__":  # pragma: no cover - CLI shim
    raise SystemExit(main())

