"""Autogenerated placeholder build module for dynamic_bookmarking."""

from __future__ import annotations

from typing import Any, Mapping

from dynamic_build_stub import build_placeholder, main_placeholder

__all__ = ("build", "main")


def build(*args: Any, **kwargs: Any) -> Mapping[str, Any]:
    """Proxy to the shared build placeholder for dynamic_bookmarking."""
    return build_placeholder("dynamic_bookmarking", *args, **kwargs)


def main() -> int:
    """Entry point for "python -m dynamic_bookmarking.build"."""
    return main_placeholder("dynamic_bookmarking")


if __name__ == "__main__":  # pragma: no cover - CLI shim
    raise SystemExit(main())

