token:
  name: Dynamic Capital Token
  symbol: DCT
  decimals: 9
  maxSupply: 100000000

splits:
  operationsPct: 60
  autoInvestPct: 30
  buybackBurnPct: 10
  bounds:
    operationsPct: [40, 75]
    autoInvestPct: [15, 45]
    buybackBurnPct: [5, 20]

locks:
  bronzeMonths: 3
  silverMonths: 6
  goldMonths: 12
  multipliers: [1.2, 1.5, 2.0]

emissions:
  epochDays: 7
  epochCap: 240000

governance:
  # Tonstarter treasury multisig (mainnet).
  multisig: "EQD1zAJPYZMYf3Y9B4SL7fRLFU-Vg5V7RcLMnEu2H_cNOPDD"
  timelockHours: 48

themePasses:
  daoMultisig: "EQCThemeDaoMultisig1111111111111111111111111111111"
  royalty:
    numerator: 500
    denominator: 10000
    destination: "EQCRoyaltySink1111111111111111111111111111111"
  plannedMints:
    - index: 0
      name: Genesis Theme Pass
      defaultPriority: 100
      contentUri: "ipfs://dynamic-capital/theme/genesis.json"
    - index: 1
      name: Growth Theme Pass
      defaultPriority: 80
      contentUri: "ipfs://dynamic-capital/theme/growth.json"
    - index: 2
      name: Community Theme Pass
      defaultPriority: 60
      contentUri: "ipfs://dynamic-capital/theme/community.json"
