token:
  name: STON.fi pTON-DCT LP
  symbol: STONFI-PTON-DCT-LP
  decimals: 9
  address: "0:31876bc3dd431f36b176f692a5e96b0ecf1aedebfa76497acd2f3661d6fbacd3"
  maxSupply: 100000000

contracts:
  # Tonstarter governance multisig exercises admin controls on-chain.
  admin: "EQD1zAJPYZMYf3Y9B4SL7fRLFU-Vg5V7RcLMnEu2H_cNOPDD"
  # Treasury receives transfer taxes and allocator forwards.
  treasury: "EQD1zAJPYZMYf3Y9B4SL7fRLFU-Vg5V7RcLMnEu2H_cNOPDD"
  # Primary STON.fi router for DCT↔TON liquidity.
  dexRouter: "EQB3ncyBUTjZUA5EnFKR5_EnOMI9V1tTEAAPaiU71gc4TiUt"

splits:
  operationsPct: 48
  autoInvestPct: 32
  buybackBurnPct: 20
  bounds:
    operationsPct: [38, 58]
    autoInvestPct: [25, 40]
    buybackBurnPct: [15, 30]
  dynamicAdjustments:
    revenueSurgeTon: 180000
    revenueSurgeBoostBps: 250
    intelligenceMomentumThreshold: 1.15
    intelligenceBurnBoostBps: 200
    floorBuybackBudgetTon: 15000
    maxAdjustmentPerEpochBps: 300

locks:
  bronzeMonths: 3
  silverMonths: 6
  goldMonths: 12
  platinumMonths: 18
  multipliers: [1.2, 1.5, 2.0, 2.5]
  loyaltyBonusBps: 75

emissions:
  epochDays: 7
  epochCap: 240000
  targetAnnualInflationPct: 4.5
  decayRateBps: 150
  floorEmission: 60000
  surgeMultiplier: 1.5

governance:
  # Tonstarter treasury multisig (mainnet).
  multisig: "EQD1zAJPYZMYf3Y9B4SL7fRLFU-Vg5V7RcLMnEu2H_cNOPDD"
  timelockHours: 48

themePasses:
  daoMultisig: "EQCThemeDaoMultisig1111111111111111111111111111111"
  royalty:
    numerator: 500
    denominator: 10000
    destination: "EQCRoyaltySink1111111111111111111111111111111"
  plannedMints:
    - index: 0
      name: Genesis Theme Pass
      defaultPriority: 100
      contentUri: "ipfs://dynamic-capital/theme/genesis.json"
    - index: 1
      name: Growth Theme Pass
      defaultPriority: 80
      contentUri: "ipfs://dynamic-capital/theme/growth.json"
    - index: 2
      name: Community Theme Pass
      defaultPriority: 60
      contentUri: "ipfs://dynamic-capital/theme/community.json"

network:
  liteservers:
    - host: 31.57.199.1
      port: 5053
      publicKeyBase64: Ug3YgtwUydgkFaxJdvtYkcsRlJZra7UrA95vOE1ZzW0=
    - host: 163.5.62.1
      port: 5053
      publicKeyBase64: Ug3YgtwUydgkFaxJdvtYkcsRlJZra7UrA95vOE1ZzW0=
