"""Dynamic AI package exposing fusion signal generation utilities."""

from .agents import (
    Agent,
    AgentResult,
    ChatAgentResult,
    ChatTurn,
    DynamicChatAgent,
    ExecutionAgent,
    ExecutionAgentResult,
    ResearchAgent,
    ResearchAgentResult,
    RiskAgent,
    RiskAgentResult,
    TradingAgent,
    TradingAgentResult,
    SpaceAgent,
    SpaceAgentResult,
)
from .core import AISignal, DynamicFusionAlgo
from .dolphin_adapter import (
    DolphinLlamaCppAdapter,
    DolphinModelConfig,
    DolphinPromptTemplate,
    DolphinSamplingConfig,
    LLMIntegrationError,
)
from .ollama_adapter import OllamaAdapter, OllamaConfig, OllamaPromptTemplate
from .analysis import AnalysisComponent, DynamicAnalysis
from .fusion import (
    FusionEngine,
    LobeSignal,
    LorentzianDistanceLobe,
    RegimeContext,
    SentimentLobe,
    SignalLobe,
    TrendMomentumLobe,
    TreasuryLobe,
)
from .training import (
    calibrate_lorentzian_lobe,
    load_lorentzian_model,
    prepare_fusion_training_rows,
)
from .risk import PositionSizing, RiskContext, RiskManager, RiskParameters
from .hedge import (
    AccountState,
    DynamicHedgePolicy,
    ExposurePosition,
    HedgeDecision,
    HedgePosition,
    MarketState,
    NewsEvent,
    VolatilitySnapshot,
)

__all__ = [
    "Agent",
    "AgentResult",
    "ChatAgentResult",
    "ChatTurn",
    "DynamicChatAgent",
    "AISignal",
    "DynamicFusionAlgo",
    "DolphinLlamaCppAdapter",
    "DolphinModelConfig",
    "DolphinPromptTemplate",
    "DolphinSamplingConfig",
    "LLMIntegrationError",
    "OllamaAdapter",
    "OllamaConfig",
    "OllamaPromptTemplate",
    "ExecutionAgent",
    "ExecutionAgentResult",
    "AnalysisComponent",
    "DynamicAnalysis",
    "ResearchAgent",
    "ResearchAgentResult",
    "FusionEngine",
    "LobeSignal",
    "LorentzianDistanceLobe",
    "RegimeContext",
    "SentimentLobe",
    "SignalLobe",
    "TrendMomentumLobe",
    "TreasuryLobe",
    "calibrate_lorentzian_lobe",
    "load_lorentzian_model",
    "prepare_fusion_training_rows",
    "PositionSizing",
    "RiskContext",
    "RiskManager",
    "RiskParameters",
    "RiskAgent",
    "RiskAgentResult",
    "TradingAgent",
    "TradingAgentResult",
    "SpaceAgent",
    "SpaceAgentResult",
    "AccountState",
    "DynamicHedgePolicy",
    "ExposurePosition",
    "HedgeDecision",
    "HedgePosition",
    "MarketState",
    "NewsEvent",
    "VolatilitySnapshot",
]
