// Generated by Framer (c105afa)
"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  SmartComponentScopedContainer,
  SVG,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import ItemList from "https://framerusercontent.com/modules/QlxpDAQvEklbpnN6f2Rb/hPTWTU33uKph6TSeeXwg/eWadg89Ed.js";
const ItemListFonts = getFonts(ItemList);
const cycleOrder = ["onHkXCb79", "hz191ZXrn"];
const serializationHash = "framer-2GOKd";
const variantClassNames = {
  hz191ZXrn: "framer-v-drjlip",
  onHkXCb79: "framer-v-i2yzfj",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach((variant) =>
    variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0, delay: 0, duration: .6, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [
    JSON.stringify(transition),
  ]);
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Not Visible": "hz191ZXrn",
  Visible: "onHkXCb79",
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant: humanReadableVariantMap[props.variant] ?? props.variant ??
      "onHkXCb79",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) {
    return variants.join("-") + props.layoutDependency;
  }
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "onHkXCb79",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } = useActiveVariantCallback(
    baseVariant,
  );
  const onTapoqibhx = activeVariantCallback(async (...args) => {
    setVariant("onHkXCb79");
  });
  const K7t2Pzfip145rnmf = activeVariantCallback(async (...args) => {
    await delay(() => setVariant("hz191ZXrn"), 200);
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-i2yzfj",
            className,
            classNames,
          ),
          "data-framer-name": "Visible",
          layoutDependency: layoutDependency,
          layoutId: "onHkXCb79",
          ref: refBinding,
          style: {
            borderBottomLeftRadius: 0,
            borderBottomRightRadius: 0,
            borderTopLeftRadius: 0,
            borderTopRightRadius: 0,
            ...style,
          },
          variants: {
            hz191ZXrn: {
              borderBottomLeftRadius: 100,
              borderBottomRightRadius: 100,
              borderTopLeftRadius: 100,
              borderTopRightRadius: 100,
            },
          },
          ...addPropertyOverrides(
            { hz191ZXrn: { "data-framer-name": "Not Visible" } },
            baseVariant,
            gestureVariant,
          ),
          children: /*#__PURE__*/ _jsx(motion.div, {
            className: "framer-186ok5x",
            "data-framer-name": "Buttons",
            layoutDependency: layoutDependency,
            layoutId: "uguYbtLlH",
            children: /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-argjgc",
              "data-border": true,
              "data-framer-name": "Filter Button",
              layoutDependency: layoutDependency,
              layoutId: "dUKm2LAhE",
              style: {
                "--border-bottom-width": "1px",
                "--border-color":
                  "var(--token-38c4cf9a-0aa8-4902-ad35-3a2d52d62d05, rgb(26, 28, 29))",
                "--border-left-width": "1px",
                "--border-right-width": "1px",
                "--border-style": "solid",
                "--border-top-width": "1px",
                backgroundColor:
                  "var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5))",
                borderBottomLeftRadius: 27,
                borderBottomRightRadius: 27,
                borderTopLeftRadius: 27,
                borderTopRightRadius: 27,
                boxShadow: "none",
              },
              variants: {
                hz191ZXrn: {
                  "--border-bottom-width": "2px",
                  "--border-left-width": "2px",
                  "--border-right-width": "2px",
                  "--border-top-width": "2px",
                  borderBottomLeftRadius: 91,
                  borderBottomRightRadius: 91,
                  borderTopLeftRadius: 91,
                  borderTopRightRadius: 91,
                  boxShadow:
                    "0px 0px 0px 2px var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5))",
                },
              },
              ...addPropertyOverrides(
                { hz191ZXrn: { "data-highlight": true, onTap: onTapoqibhx } },
                baseVariant,
                gestureVariant,
              ),
              children: [
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-1wbt4hy",
                  "data-framer-name": "Icon",
                  layoutDependency: layoutDependency,
                  layoutId: "QQ9vFstPF",
                  style: {
                    filter: "blur(5px)",
                    opacity: 0,
                    WebkitFilter: "blur(5px)",
                  },
                  variants: {
                    hz191ZXrn: {
                      filter: "blur(0px)",
                      opacity: 1,
                      WebkitFilter: "blur(0px)",
                    },
                  },
                  children: /*#__PURE__*/ _jsx(SVG, {
                    className: "framer-vkmqdk",
                    "data-framer-name": "Graphic",
                    layout: "position",
                    layoutDependency: layoutDependency,
                    layoutId: "azz8flJFH",
                    opacity: 1,
                    svg:
                      '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 18 18"><path d="M 2.25 6 C 2.25 5.586 2.586 5.25 3 5.25 L 15 5.25 C 15.414 5.25 15.75 5.586 15.75 6 C 15.75 6.414 15.414 6.75 15 6.75 L 3 6.75 C 2.586 6.75 2.25 6.414 2.25 6 Z M 6 12 C 6 11.586 6.149 11.25 6.333 11.25 L 11.667 11.25 C 11.851 11.25 12 11.586 12 12 C 12 12.414 11.851 12.75 11.667 12.75 L 6.333 12.75 C 6.15 12.75 6 12.414 6 12 Z M 4.5 9 C 4.5 8.586 4.724 8.25 5 8.25 L 13 8.25 C 13.276 8.25 13.5 8.586 13.5 9 C 13.5 9.414 13.276 9.75 13 9.75 L 5 9.75 C 4.724 9.75 4.5 9.414 4.5 9 Z" fill="var(--token-84002464-baa0-40a1-a1a1-82899aec539a, rgb(155, 161, 165)) /* {&quot;name&quot;:&quot;11&quot;} */"></path></svg>',
                    svgContentId: 11110314899,
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      { hz191ZXrn: { svgContentId: 10901956737 } },
                      baseVariant,
                      gestureVariant,
                    ),
                  }),
                }),
                /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                  height: 324,
                  width: "290px",
                  y: (componentViewport?.y || 0) + 0 +
                    (((componentViewport?.height || 324) - 0) *
                        .5000000000000002 - 162) +
                    0,
                  ...addPropertyOverrides(
                    {
                      hz191ZXrn: {
                        y: (componentViewport?.y || 0) + 0 + 0 +
                          (((componentViewport?.height || 48) - 0 - 0) *
                              .5000000000000002 - 162),
                      },
                    },
                    baseVariant,
                    gestureVariant,
                  ),
                  children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                    className: "framer-vhbqig-container",
                    layoutDependency: layoutDependency,
                    layoutId: "JSt9dmKnI-container",
                    nodeId: "JSt9dmKnI",
                    rendersWithMotion: true,
                    scopeId: "P7CrQl6QJ",
                    style: { opacity: 1 },
                    variants: { hz191ZXrn: { opacity: 0 } },
                    children: /*#__PURE__*/ _jsx(ItemList, {
                      height: "100%",
                      id: "JSt9dmKnI",
                      K7t2Pzfip: K7t2Pzfip145rnmf,
                      layoutId: "JSt9dmKnI",
                      style: { height: "100%", width: "100%" },
                      variant: "SNmZ3YsTs",
                      width: "100%",
                      ...addPropertyOverrides(
                        { hz191ZXrn: { K7t2Pzfip: undefined } },
                        baseVariant,
                        gestureVariant,
                      ),
                    }),
                  }),
                }),
              ],
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-2GOKd.framer-e5xj44, .framer-2GOKd .framer-e5xj44 { display: block; }",
  ".framer-2GOKd.framer-i2yzfj { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 324px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 290px; }",
  ".framer-2GOKd .framer-186ok5x { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; z-index: 1; }",
  ".framer-2GOKd .framer-argjgc { flex: none; height: 324px; left: calc(50.00000000000002% - 290px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 324px / 2); width: 290px; will-change: var(--framer-will-change-override, transform); z-index: 5; }",
  ".framer-2GOKd .framer-1wbt4hy { flex: none; height: 32px; left: calc(50.00000000000002% - 32px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 32px / 2); width: 32px; }",
  ".framer-2GOKd .framer-vkmqdk { flex: none; height: 18px; left: calc(50.00000000000002% - 18px / 2); position: absolute; top: calc(46.87500000000002% - 18px / 2); width: 18px; z-index: 4; }",
  ".framer-2GOKd .framer-vhbqig-container { flex: none; height: 324px; left: calc(50.00000000000002% - 290px / 2); position: absolute; top: calc(50.00000000000002% - 324px / 2); width: 290px; z-index: 1; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-2GOKd.framer-i2yzfj { gap: 0px; } .framer-2GOKd.framer-i2yzfj > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-2GOKd.framer-i2yzfj > :first-child { margin-left: 0px; } .framer-2GOKd.framer-i2yzfj > :last-child { margin-right: 0px; } }",
  ".framer-2GOKd.framer-v-drjlip.framer-i2yzfj { height: 48px; overflow: visible; width: 48px; }",
  ".framer-2GOKd.framer-v-drjlip .framer-186ok5x { order: 0; overflow: visible; }",
  ".framer-2GOKd.framer-v-drjlip .framer-argjgc { bottom: 0px; cursor: pointer; height: unset; left: 0px; right: 0px; top: 0px; width: unset; }",
  ".framer-2GOKd.framer-v-drjlip .framer-vkmqdk { top: calc(50.00000000000002% - 18px / 2); }",
  ".framer-2GOKd.framer-v-drjlip .framer-vhbqig-container { left: calc(52.08333333333336% - 290px / 2); pointer-events: none; }",
  '.framer-2GOKd[data-border="true"]::after, .framer-2GOKd [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
]; /**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 324
 * @framerIntrinsicWidth 290
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"hz191ZXrn":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */

const FramerP7CrQl6QJ = withCSS(Component, css, "framer-2GOKd");
export default FramerP7CrQl6QJ;
FramerP7CrQl6QJ.displayName = "Filter Component";
FramerP7CrQl6QJ.defaultProps = { height: 324, width: 290 };
addPropertyControls(FramerP7CrQl6QJ, {
  variant: {
    options: ["onHkXCb79", "hz191ZXrn"],
    optionTitles: ["Visible", "Not Visible"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(FramerP7CrQl6QJ, [
  { explicitInter: true, fonts: [] },
  ...ItemListFonts,
], { supportsExplicitInterCodegen: true });
export const __FramerMetadata__ = {
  "exports": {
    "default": {
      "type": "reactComponent",
      "name": "FramerP7CrQl6QJ",
      "slots": [],
      "annotations": {
        "framerImmutableVariables": "true",
        "framerComponentViewportWidth": "true",
        "framerColorSyntax": "true",
        "framerIntrinsicWidth": "290",
        "framerCanvasComponentVariantDetails":
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"hz191ZXrn":{"layout":["fixed","fixed"]}}}',
        "framerDisplayContentsDiv": "false",
        "framerContractVersion": "1",
        "framerIntrinsicHeight": "324",
      },
    },
    "Props": {
      "type": "tsType",
      "annotations": { "framerContractVersion": "1" },
    },
    "__FramerMetadata__": { "type": "variable" },
  },
};
//# sourceMappingURL=./P7CrQl6QJ.map
