-- TON wallet telemetry persistence

create table if not exists public.ton_wallet_summaries (
  id uuid primary key default gen_random_uuid(),
  wallet_address text not null,
  owner text not null,
  risk_tier text not null,
  tags text[] not null default '{}',
  total_value_usd numeric(30,6) not null,
  available_value_usd numeric(30,6) not null,
  buffer_ratio numeric(18,8) not null,
  diversification_score numeric(18,8) not null,
  exposures jsonb not null,
  actions jsonb not null,
  alerts text[] not null,
  account_state jsonb not null,
  price_map jsonb not null,
  observed_at timestamptz not null,
  ton_price_source text,
  ton_price_usd numeric(18,8),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (wallet_address, observed_at)
);

create index if not exists ton_wallet_summaries_observed_idx
  on public.ton_wallet_summaries (observed_at desc);

create table if not exists public.ton_wallet_alerts (
  wallet_address text not null,
  alert text not null,
  observed_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (wallet_address, alert, observed_at)
);

alter table public.ton_wallet_summaries enable row level security;
alter table public.ton_wallet_alerts enable row level security;

create policy if not exists "Service role manages ton_wallet_summaries" on public.ton_wallet_summaries
  for all to service_role using (true) with check (true);

create policy if not exists "Service role manages ton_wallet_alerts" on public.ton_wallet_alerts
  for all to service_role using (true) with check (true);

comment on table public.ton_wallet_summaries is 'Wallet health snapshots generated by the TON wallet engine.';
comment on table public.ton_wallet_alerts is 'Alerts emitted by TON wallet health evaluations.';
