-- Market intelligence data tables for fundamentals, sentiment, and COT reports

create table if not exists public.market_news (
  id bigint generated by default as identity primary key,
  source text,
  headline text,
  event_time timestamptz,
  impact text,
  currency text,
  forecast text,
  actual text,
  created_at timestamptz not null default now()
);

create index if not exists market_news_event_time_idx
  on public.market_news (event_time desc nulls last);

alter table public.market_news enable row level security;

create policy market_news_service_role_full_access
  on public.market_news
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create table if not exists public.sentiment (
  id bigint generated by default as identity primary key,
  source text,
  symbol text,
  sentiment numeric(10,4),
  long_percent numeric(10,4),
  short_percent numeric(10,4),
  created_at timestamptz not null default now()
);

create index if not exists sentiment_symbol_idx
  on public.sentiment (symbol);

create index if not exists sentiment_created_at_idx
  on public.sentiment (created_at desc);

alter table public.sentiment enable row level security;

create policy sentiment_service_role_full_access
  on public.sentiment
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create table if not exists public.cot_reports (
  id bigint generated by default as identity primary key,
  market text,
  commercial_long bigint,
  commercial_short bigint,
  noncommercial_long bigint,
  noncommercial_short bigint,
  date date,
  created_at timestamptz not null default now()
);

create index if not exists cot_reports_market_date_idx
  on public.cot_reports (market, date desc nulls last);

alter table public.cot_reports enable row level security;

create policy cot_reports_service_role_full_access
  on public.cot_reports
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
