-- Create table for storing normalised market depth snapshots from multiple providers
create table if not exists public.market_depth_snapshots (
    id bigint generated by default as identity primary key,
    symbol text not null,
    provider text not null,
    source text not null,
    bid_price double precision not null,
    ask_price double precision not null,
    mid_price double precision not null,
    spread_bps double precision not null,
    depth_usd double precision not null,
    bid_volume double precision not null,
    ask_volume double precision not null,
    tick_volume double precision not null,
    observed_at timestamptz not null,
    created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists market_depth_snapshots_symbol_observed_provider_idx
    on public.market_depth_snapshots(symbol, observed_at, provider);
