-- Add descriptive comments for key application tables
comment on table public.abuse_bans is 'Moderation ledger storing Telegram users who are temporarily or permanently blocked from the Dynamic Capital bot.';
comment on table public.admin_logs is 'Immutable audit trail of privileged administrative actions taken through the platform.';
comment on table public.auto_reply_templates is 'Preconfigured response templates that drive automated replies based on trigger conditions.';
comment on table public.bank_accounts is 'Bank payout accounts and wiring instructions presented to customers for fiat settlements.';
comment on table public.bot_content is 'Central repository for Dynamic Capital bot copy, scripts, and knowledge snippets.';
comment on table public.bot_sessions is 'Runtime telemetry for each bot session, including activity counts and lifecycle timestamps.';
comment on table public.bot_settings is 'Feature toggles and configuration values that control bot behaviour at runtime.';
comment on table public.bot_users is 'Telegram user registry containing identity, subscription, and follow-up metadata.';
comment on table public.broadcast_messages is 'Queued announcements and bulk messages distributed to Dynamic Capital broadcast audiences.';
comment on table public.channel_memberships is 'Links users to gated broadcast or discussion channels tied to their subscription plan.';
comment on table public.chat_messages is 'Message history for interactive chat sessions between users and Dynamic Capital assistants.';
comment on table public.chat_sessions is 'Conversation session records that group chat messages and capture context metadata.';
comment on table public.contact_links is 'Curated contact and call-to-action links surfaced inside the Telegram bot experience.';
comment on table public.conversion_tracking is 'Attribution dataset logging promo clicks and conversions for marketing funnels.';
comment on table public.daily_analytics is 'Daily aggregated analytics covering growth, retention, and engagement KPIs.';
comment on table public.domain_resolution_cache is 'Cached DNS and resolver lookups to accelerate repeated domain availability checks.';
comment on table public.education_categories is 'Top-level categories used to organise education packages in the academy.';
comment on table public.education_enrollments is 'Enrollment records mapping learners to Dynamic Capital education packages and progress.';
comment on table public.education_packages is 'Catalog of structured education products, modules, and bundled lessons.';
comment on table public.email_campaigns is 'Outbound email campaign definitions, scheduling metadata, and creative settings.';
comment on table public.email_recipients is 'Recipient targeting lists and delivery state for each email campaign send.';
comment on table public.email_templates is 'Reusable HTML and text templates that power branded outbound email.';
comment on table public.enrollment_audit_log is 'Change history capturing who altered education enrollments and when.';
comment on table public.kv_config is 'General-purpose key/value configuration store consumed across services.';
comment on table public.media_files is 'Metadata for media assets uploaded to storage and referenced by the platform.';
comment on table public.payment_intents is 'Initiated payment attempts with provider references and expected settlement state.';
comment on table public.payments is 'Payment processing table - Stripe integration removed, supports crypto, Binance Pay, bank transfers, and manual payments only.';
comment on table public.plan_channels is 'Mapping between subscription plans and the Telegram channels or chats they unlock.';
comment on table public.profiles is 'Extended profile information for authenticated users beyond Telegram basics.';
comment on table public.promo_analytics is 'Roll-up analytics tracking the performance of promotions and referral funnels.';
comment on table public.promotion_usage is 'Usage ledger counting how often each promotion code has been redeemed.';
comment on table public.promotions is 'Definition of promotional codes, discounts, and availability windows.';
comment on table public.session_audit_log is 'Audit trail for authentication sessions to support security investigations.';
comment on table public.subdomain_claims is 'User-submitted claims for Dynamic Capital branded subdomains awaiting approval.';
comment on table public.subscription_audit_log is 'Audit log recording lifecycle changes to user subscriptions and billing events.';
comment on table public.subscription_plans is 'Catalog of available subscription plans, pricing, and entitlement metadata.';
comment on table public.ton_subdomains is 'Registry of TON subdomains minted or reserved through Dynamic Capital infrastructure.';
comment on table public.ton_transactions is 'On-chain transaction records sourced from the TON payment rails and wallets.';
comment on table public.user_analytics is 'Aggregated analytics features capturing user-level engagement signals.';
comment on table public.user_interactions is 'Event stream of user interactions with the Telegram bot and its features.';
comment on table public.user_package_assignments is 'Assignments linking users to premium package entitlements and delivery status.';
comment on table public.user_sessions is 'Session metadata for authenticated app usage, including device and timing details.';
comment on table public.user_subscriptions is 'Active and historical subscription records with plan, status, and renewal data.';
comment on table public.user_surveys is 'Survey responses collected from users for feedback and research initiatives.';
