// This file is automatically generated. Do not edit it directly.
import { createClient, getQueryCounts, SUPABASE_URL, SUPABASE_ANON_KEY } from "../../../shared/supabase-client.ts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = SUPABASE_URL && SUPABASE_ANON_KEY ? createClient() : ({} as any);
export { getQueryCounts };
