name: Supabase Project Audit
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1" # Mondays 03:00 UTC

permissions:
  contents: read
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            apps/*/package-lock.json
      - name: Run Audit
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          node -v
          npm -v
          chmod +x scripts/audit/run.sh
          ./scripts/audit/run.sh
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: audit-report
          path: .audit/*
