name: Metadata Audit
permissions:
  contents: read

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup runtimes
        uses: ./.github/actions/setup-runtimes
        with:
          enable-node: "true"
          node-version: "20"
          node-cache: npm
      - run: npm ci
      - run: npm run audit:metadata
        env:
          A_SUPABASE_URL: ${{ secrets.A_SUPABASE_URL }}
          A_SUPABASE_KEY: ${{ secrets.A_SUPABASE_KEY }}
      - uses: actions/upload-artifact@v5
        with:
          name: metadata-audit
          path: .audit
