name: Auto-merge labeled PRs
on:
  pull_request:
    types: [opened, labeled, synchronize, ready_for_review, reopened]
permissions:
  contents: write
  pull-requests: write
jobs:
  enable:
    if: contains(github.event.pull_request.labels.*.name, 'automerge-candidate')
    runs-on: ubuntu-latest
    steps:
      - name: Enable native auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: SQUASH
