name: Auto-merge labeled PRs
on:
  pull_request:
    types: [opened, labeled, synchronize, ready_for_review, reopened]
permissions:
  contents: write
  pull-requests: write
jobs:
  paths:
    runs-on: ubuntu-latest
    outputs:
      content_changed: ${{ steps.filter.outputs.content }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            content:
              - 'content/**'
              - 'docs/**'
              - 'pages/**'
              - 'app/**/team/**'
              - 'app/**/about/**'
  enable:
    needs: paths
    if: >-
      contains(github.event.pull_request.labels.*.name, 'automerge-candidate') &&
      !contains(github.event.pull_request.labels.*.name, 'needs-sources') &&
      !contains(github.event.pull_request.labels.*.name, 'no-fakes') &&
      !contains(github.event.pull_request.labels.*.name, 'content') &&
      needs.paths.outputs.content_changed != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Enable native auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: SQUASH
