name: Enable Auto Merge

on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - opened
      - reopened

permissions:
  pull-requests: write
  contents: write

jobs:
  enable:
    if: github.event.action == 'labeled' && github.event.label.name == 'automerge-candidate'
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash

  disable:
    if: github.event.action == 'unlabeled' && github.event.label.name == 'automerge-candidate'
    runs-on: ubuntu-latest
    steps:
      - name: Disable auto-merge
        uses: peter-evans/disable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
