name: Deno Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    env:
      DENO_TLS_CA_STORE: system
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno check supabase/functions/telegram-bot/*.ts supabase/functions/telegram-bot/**/*.ts
