name: Deno Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: read-all

jobs:
  typecheck:
    runs-on: ubuntu-latest
    env:
      DENO_TLS_CA_STORE: system
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: denoland/setup-deno@11b63cf76cfcafb4e43f97b6cad24d8e8438f62d
        with:
          deno-version: v1.x
      - name: Build & bundle miniapp
        run: |
          export PROJECT_REF=qeejuomcapbdlhnjqjcc
          npm run build:miniapp
          npm run bundle:miniapp
          npm run assert:miniapp
      - run: deno check supabase/functions/telegram-bot/*.ts supabase/functions/telegram-bot/**/*.ts
  miniapp-packaging:
    runs-on: ubuntu-latest
    env:
      DENO_TLS_CA_STORE: system
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: denoland/setup-deno@11b63cf76cfcafb4e43f97b6cad24d8e8438f62d
        with:
          deno-version: v1.x
      - name: Build & bundle miniapp
        run: |
          export PROJECT_REF=qeejuomcapbdlhnjqjcc
          npm run build:miniapp
          npm run bundle:miniapp
          npm run assert:miniapp
      - run: deno test tests/miniapp-packaging.test.ts
