name: CI Deploy DC

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      DENO_TLS_CA_STORE: system
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Cache Deno dependencies
        id: deno-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/deno
            ~/.deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock', 'deno.json') }}
          restore-keys: |
            ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}-
            ${{ runner.os }}-deno-
      - name: Report Deno cache status
        env:
          CACHE_HIT: ${{ steps.deno-cache.outputs.cache-hit }}
        run: |
          echo "Deno cache hit: ${CACHE_HIT:-false}"
          {
            echo "### CI Deploy DC cache";
            echo "- Cache hit: \`${CACHE_HIT:-false}\`";
          } >> "$GITHUB_STEP_SUMMARY"
      - name: CI (fmt/lint/typecheck/test)
        run: bash scripts/ci.sh
        continue-on-error: true
      - name: Auto-fix formatting on PR
        if: ${{ github.event_name == 'pull_request' }}
        env:
          AUTO_FMT: "1"
          DENO_TLS_CA_STORE: system
        run: |
          chmod +x scripts/ci.sh || true
          # Run only the fmt portion with AUTO_FMT=1
          if ! deno fmt --check supabase/functions src; then
            deno fmt supabase/functions src
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(format): apply deno fmt" || echo "Nothing to commit"
          fi
