name: migrations-check

on:
  push: {}
  pull_request: {}

permissions:
  contents: read

jobs:
  migrations-check:
    name: migrations-check
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
      - name: Validate migrations
        run: |
          npx drizzle-kit check || npm run migrate:check
