name: Ops Sync

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup runtimes
        uses: ./.github/actions/setup-runtimes
        with:
          enable-node: "true"
          node-version: "22"
          node-cache: npm
          node-cache-dependency-path: |
            package-lock.json
            apps/*/package-lock.json
          enable-deno: "true"
          deno-version: v1.x
          deno-cache-key: ${{ format('{0}-deno-{1}', runner.os, hashFiles('deno.lock')) }}
          deno-cache-restore-keys: |
            ${{ format('{0}-deno-', runner.os) }}
          write-summary: "true"
      - run: npm ci
      - run: npm test
      - name: Sync audit
        if: ${{ secrets.SUPABASE_ACCESS_TOKEN != '' && secrets.SUPABASE_PROJECT_REF != '' && secrets.ADMIN_API_SECRET != '' }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          ADMIN_API_SECRET: ${{ secrets.ADMIN_API_SECRET }}
        run: scripts/ops/sync-audit.sh
      - name: Smoke test
        if: always()
        run: scripts/ops/smoke.sh
