name: Ops Sync

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions: read-all

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 20
      - uses: denoland/setup-deno@11b63cf76cfcafb4e43f97b6cad24d8e8438f62d
        with:
          deno-version: v1.x
      - run: npm ci
      - run: npm test
      - name: Sync audit
        if: ${{ secrets.SUPABASE_ACCESS_TOKEN != '' && secrets.SUPABASE_PROJECT_REF != '' && secrets.ADMIN_API_SECRET != '' }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          ADMIN_API_SECRET: ${{ secrets.ADMIN_API_SECRET }}
        run: scripts/ops/sync-audit.sh
      - name: Smoke test
        if: always()
        run: scripts/ops/smoke.sh
