name: reviewer-nudge
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write
jobs:
  nudge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping stale PRs with awaiting-review
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NOW=$(date -u +%s)
          gh pr list --state open --label awaiting-review --json number,updatedAt,title \
            | jq -c '.[]' | while read -r pr; do
              num=$(echo "$pr" | jq -r .number)
              updated=$(echo "$pr" | jq -r .updatedAt)
              age=$(( (NOW - $(date -u -d "$updated" +%s)) / 3600 ))
              if [ "$age" -ge 48 ]; then
                gh pr comment "$num" -b "⏰ Gentle reminder: checklist still pending. Please review and check items in \`docs/dynamic-capital-checklist.md\`."
              fi
            done
