name: TONCenter Schema Audit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # Daily at 06:00 UTC

permissions:
  contents: read

jobs:
  audit:
    name: Audit TONCenter schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx

      - name: Run schema guard
        env:
          # TONCENTER schema guard accounts:
          # - EQDSmz4RrDBFG-T1izwVJ7q1dpAq1mJTLrKwyMYJig6Wx_6y (DCT jetton master)
          # - EQAmzcKg3eybUNzsT4llJrjoDe7FwC51nSRhJEMACCdniYhq (DCT treasury jetton wallet)
          # - EQB3ncyBUTjZUA5EnFKR5_EnOMI9V1tTEAAPaiU71gc4TiUt (STON.fi TON→DCT router)
          # 2025-10-09 watchlist expansion (pending attribution):
          # - EQDyAmBSxP1-D--D9GBazb0-MNmZ8ecttc_njImeEzt_heIA – Auxiliary liquidity routing.
          # - EQDz0wQL6EEdgbPkFgS7nNmywzr468AvgLyhH7PIMALxPB6G – Awaiting tonviewer label review.
          # - EQDz5SDaF1B8jGEfthlLjVzkByQPbG-FStBVEHAFmS_3wZ-O – Settlement and emissions side-flow monitor.
          # - EQD1BCRMqIkSzt3XpWGORH_HvX5lHNbpDDtvzCGdDoArGYQn – Candidate treasury satellite wallet.
          # - EQD1mjivKNskrad8FQV8UtNAC6ayMB5bgv6rYmhOcSKPLjZc – Staking / lockbox disbursement checks.
          # - EQD2dUSfVIJVT77aBEIjXBe_Z1oj9Kwh40TngDmTEol0l68b – Swap routing validation.
          # - EQD5xwKMuP4X39iy7Ta79x9QBB4U0pds25eEfuLS6O5icwgy – High-volume transfer confirmation.
          # - EQD6JaMgi4nf1YpdSyYV5SoIvYPhDNqdUGrgZeRJbjMqJxKD – Ownership tracing in progress.
          # - EQD6Tv6Kbqp-RYPl_T9Rum_pixdFX71IC83doVRu0fIqv50d – Contract interaction tracing.
          # - EQD7y8d1ImET4WqHclpIJVED2WHKCXb4U3riNV6spyWmzuya – Derivative routing surveillance.
          # - EQD9flc1cUiQA-gpEx9J9AsVmRp-VbjP4z4eTLZ5fsfvTGFi – Cross-program transfer monitoring.
          # - EQD-mBBkUdiPEbkdli268DKsQxNMyPNHD7aDMSwliXG57SFy – Hold until schema deltas stabilise.
          TONCENTER_SCHEMA_ACCOUNTS: |
            EQDSmz4RrDBFG-T1izwVJ7q1dpAq1mJTLrKwyMYJig6Wx_6y
            EQAmzcKg3eybUNzsT4llJrjoDe7FwC51nSRhJEMACCdniYhq
            EQB3ncyBUTjZUA5EnFKR5_EnOMI9V1tTEAAPaiU71gc4TiUt
            EQDyAmBSxP1-D--D9GBazb0-MNmZ8ecttc_njImeEzt_heIA
            EQDz0wQL6EEdgbPkFgS7nNmywzr468AvgLyhH7PIMALxPB6G
            EQDz5SDaF1B8jGEfthlLjVzkByQPbG-FStBVEHAFmS_3wZ-O
            EQD1BCRMqIkSzt3XpWGORH_HvX5lHNbpDDtvzCGdDoArGYQn
            EQD1mjivKNskrad8FQV8UtNAC6ayMB5bgv6rYmhOcSKPLjZc
            EQD2dUSfVIJVT77aBEIjXBe_Z1oj9Kwh40TngDmTEol0l68b
            EQD5xwKMuP4X39iy7Ta79x9QBB4U0pds25eEfuLS6O5icwgy
            EQD6JaMgi4nf1YpdSyYV5SoIvYPhDNqdUGrgZeRJbjMqJxKD
            EQD6Tv6Kbqp-RYPl_T9Rum_pixdFX71IC83doVRu0fIqv50d
            EQD7y8d1ImET4WqHclpIJVED2WHKCXb4U3riNV6spyWmzuya
            EQD9flc1cUiQA-gpEx9J9AsVmRp-VbjP4z4eTLZ5fsfvTGFi
            EQD-mBBkUdiPEbkdli268DKsQxNMyPNHD7aDMSwliXG57SFy
          TONCENTER_API_KEY: ${{ secrets.TONCENTER_API_KEY }}
        run: |
          python -m dynamic_ton.schema_guard_runner \
            --limit 50 \
            --include-accounts \
            --output-json schema-report.json \
            --allow-drift

      - name: Upload schema report
        uses: actions/upload-artifact@v4
        with:
          name: toncenter-schema-report
          path: schema-report.json

      - name: Summarise schema audit
        run: |
          python - <<'PY'
          import json
          import os
          from pathlib import Path

          from dynamic_ton.schema_guard_runner import render_summary_markdown

          report_path = Path("schema-report.json")
          data = json.loads(report_path.read_text())

          summary_path = Path(os.environ["GITHUB_STEP_SUMMARY"])
          with summary_path.open("a", encoding="utf-8") as handle:
              handle.write(render_summary_markdown(data))

          if data.get("has_drift"):
              raise SystemExit("Schema drift detected; review unknown fields above.")
          PY
