name: Bot & MiniApp Verification
on:
  pull_request:
  workflow_dispatch:

permissions: read-all
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Run verification
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: bash scripts/verify/verify_all.sh
      - name: Upload report artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: verify-report
          path: .out/verify_report.md
